### ISSUE TITLE
执行第一步就出错了

### ISSUE THREAD

**Issue by johnenvpath** [Robinsir/BTSOW#1]
G:\Program Files\BTSOW-dev>npm install

> btsow@0.0.1 postinstall G:\Program Files\BTSOW-dev
> npm run lint:fix

> btsow@0.0.1 lint:fix G:\Program Files\BTSOW-dev
> eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src

  ✘  http://eslint.org/docs/rules/new-cap  A constructor name should not start with a lowercase letter
  src\main\module\BaiduYun.js:10:23
      let pcs = new PCS['default'](PCS.create_username_password_jar_creator(usrName, passWord,
                         ^

✘ 1 problem (1 error, 0 warnings)

Errors:
  1  http://eslint.org/docs/rules/new-cap
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! btsow@0.0.1 lint:fix: `eslint --ext .js,.vue -f ./node_modules/eslint-friendly-formatter --fix src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the btsow@0.0.1 lint:fix script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\John Wayne\AppData\Roaming\npm-cache\_logs\2019-02-12T07_16_19_253Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! btsow@0.0.1 postinstall: `npm run lint:fix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the btsow@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\John Wayne\AppData\Roaming\npm-cache\_logs\2019-02-12T07_16_19_298Z-debug.log

npm版本6.5.0，Windows10教育版x64

**Comment by Robinsir** [comment]
eslint 问题，已修复
